# Generated by Django 4.1.5 on 2023-01-05 16:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
